# Programa Ingenias+ Data Science

Como dijimos en clases anteriores, Python tiene implementadas muchas librerias para poder trabajar con datos. En la clase de hoy trabajaremos con una de ellas: `Numpy`.

Antes de comenzar, vamos a hablar un poco de esta libreria o modulo.

**Numpy** es una librería optimizada para realizar cálculos numéricos con vectores y matrices. A diferencia de otros lenguajes de programación, Python no posee en su estructura central la figura de matrices. Eso quiere decir que para poder trabajar con esta estructura de datos deberiamos trabajar con listas de listas. NumPy introduce el concepto de arrays o matrices.

Al ser de código abierto, `numpy` posee una documentación muy amplia que es **SIEMPRE RECOMENDABLE** consultar.

- [Documentacion NumPy](https://devdocs.io/numpy/)

## Clase 4: Introduccion a NumPy

# Ejercicios

1. Crear un arreglo de ceros de longitud 12
2. Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
3. Crear un arreglo que tenga los números del 10 al 49
4. Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
5. Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
6. Calcular la media de un arreglo usando np.sum
7. Calcular la varianza de un arreglo usando np.sum y np.mean
8. Crear un array de números aleatorios usando np.random.randn.


In [1]:
import numpy as np

1) Crear un arreglo de ceros de longitud 12

In [2]:
arreglo_ceros = np.zeros(12)
print(arreglo_ceros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


2) Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5

In [3]:
arreglo = np.zeros(10)
arreglo[4] = 10  # La posición número 5 tiene índice 4
print(arreglo)

[ 0.  0.  0.  0. 10.  0.  0.  0.  0.  0.]


3) Crear un arreglo que tenga los números del 10 al 49

In [4]:
arreglo = np.arange(10, 50) #numpy.arange() de NumPy es una función que permite generar una secuencia de números especificando un valor inicial, un valor final y un paso (opcional)
print(arreglo)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


4) Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8

In [5]:
# Primero creo un arreglo 1D con los números del 0 al 8
arreglo_1d = np.arange(9)
# Luego usando Reshape para convertirlo en un arreglo 2D de forma (3, 3)
arreglo_2d = arreglo_1d.reshape((3, 3))

print(arreglo_2d)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


5) Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza

In [9]:
# Creo un arreglo de 100 números aleatorios entre 0 y 1
arreglo_aleatorio = np.random.rand(100)

# Calculo la media y la varianza del arreglo
media = np.mean(arreglo_aleatorio)
varianza = np.var(arreglo_aleatorio)

print("Arreglo de números aleatorios:")
print(arreglo_aleatorio)
print("\nMedia:", media)
print("Varianza:", varianza)

Arreglo de números aleatorios:
[0.6292802  0.31500123 0.76109625 0.87095264 0.26244046 0.02554053
 0.26863013 0.15824326 0.61950153 0.95175945 0.5383425  0.00482191
 0.01143679 0.09397638 0.0012918  0.98227157 0.04362428 0.07475206
 0.63924034 0.43448052 0.14049842 0.62565283 0.61390977 0.11222218
 0.73294531 0.17726655 0.11637668 0.654108   0.15299066 0.40947864
 0.74721764 0.02349755 0.66096831 0.93784809 0.20621973 0.87349555
 0.31254452 0.46840846 0.24641551 0.57997104 0.37296366 0.47162281
 0.77741674 0.73534989 0.53522696 0.46142353 0.75385439 0.32966667
 0.3414861  0.59628702 0.28800553 0.48798282 0.79370973 0.03246468
 0.43416442 0.25670749 0.95342015 0.32664184 0.87344419 0.89501275
 0.66701434 0.63560717 0.13291374 0.7128617  0.4384157  0.4037347
 0.66829238 0.90369728 0.16436759 0.4131964  0.43611817 0.94373231
 0.73792653 0.57161372 0.79582379 0.70591238 0.95207125 0.4484811
 0.74317074 0.25442209 0.9247134  0.54815913 0.47374116 0.21940766
 0.52595369 0.4295745  0.6254039 

6) Calcular la media de un arreglo usando np.sum

In [11]:
# Creo un arreglo
arreglo = np.array([1, 2, 3, 4, 5])
# Calculo la media utilizando np.sum y len
media = np.sum(arreglo) / len(arreglo) #np.sum(arreglo)suma todos los elementos del arreglo, y len(arreglo) devuelve la cantidad de elementos en el arreglo

print("Arreglo:", arreglo)
print("Media:", media)

Arreglo: [1 2 3 4 5]
Media: 3.0


7) Calcular la varianza de un arreglo usando np.sum y np.mean

In [12]:
# Calculo las diferencias entre cada elemento y la media
diferencias = arreglo - media
# Calcular el cuadrado de las diferencias
cuadrados_diferencias = diferencias**2
# Calcular la varianza utilizando np.sum y np.mean
varianza = np.sum(cuadrados_diferencias) / len(arreglo)
print("Arreglo:", arreglo)
print("Varianza:", varianza)

Arreglo: [1 2 3 4 5]
Varianza: 2.0


8) Crear un array de números aleatorios usando np.random.randn.

In [13]:
arreglo_aleatorio = np.random.randn(10)
print(arreglo_aleatorio)

[-1.57584987  1.12382573  1.53036932 -2.60591342  1.41443813 -1.46166754
 -1.59296827 -0.43640587  0.08030784 -2.00808925]
